services:
  db:
    image: postgres:17.4
    container_name: ctenex_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - ctenex_data:/var/lib/postgresql/ctenex_data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ctenex:/app/ctenex  # Hot reload

volumes:
  ctenex_data:
  ctenex:
